# Generated by Django 4.0.3 on 2022-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=2, max_length=200, verbose_name='Nom'),
            preserve_default=False,
        ),
    ]
